FROM ruby:2.5.1 AS base

# Install system dependencies required both at runtime and build time
# The image uses Postgres but you can swap it with mariadb-dev (for MySQL) or sqlite-dev
# RUN apk add --update \
#   postgresql-dev \
#   tzdata \
#   nodejs

# This stage will be responsible for installing gems
# FROM base AS dependencies

# Install system dependencies required to build some Ruby gems (pg)
# RUN apk add --update build-base

COPY Gemfile Gemfile.lock ./

# RUN gem install bundler bundler:2.1.4

# Install gems (excluding development/test dependencies)
RUN bundle config set without "test" && \
  bundle install

COPY package.json package-lock.json ./

RUN npm install  --frozen-lockfile

# We're back at the base stage
FROM base

# Create a non-root user to run the app and own app-specific files
RUN adduser -D app

# Switch to this user
# USER app

# We'll install the app in this directory
# WORKDIR /home/app

# Copy over gems from the dependencies stage
COPY --from=dependencies /usr/local/bundle/ /usr/local/bundle/

COPY --chown=app --from=dependencies /node_modules/ node_modules/

# Finally, copy over the code
# This is where the .dockerignore file comes into play
# Note that we have to use `--chown` here
COPY --chown=app . ./

RUN RAILS_ENV=development SECRET_KEY_BASE=assets bundle exec rake assets:precompile

# Launch the server (or run some other Ruby command)
CMD ["bundle", "exec", "rails", "server"]